name: amz_mlflow
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - alembic=1.12.0
  - arrow-cpp=11.0.0
  - asttokens=2.4.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.0.1
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.4
  - configparser=5.3.0
  - contourpy=1.1.1
  - cryptography=41.0.4
  - cycler=0.11.0
  - databricks-cli=0.17.8
  - debugpy=1.8.0
  - decorator=5.1.1
  - docker-py=6.1.3
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - flask=2.3.3
  - fonttools=4.43.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gflags=2.2.2
  - gitdb=4.0.10
  - gitpython=3.1.37
  - glib=2.78.0
  - glib-tools=2.78.0
  - glog=0.5.0
  - greenlet=2.0.2
  - grpc-cpp=1.48.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - intel-openmp=2022.1.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - itsdangerous=2.1.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.3.1
  - jupyter_core=5.3.2
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-devel=1.82.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.88.1
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.2.4
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2022.1.0
  - mlflow=2.7.1
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numpy=1.24.4
  - oauthlib=3.2.2
  - openssl=3.1.3
  - orc=1.7.4
  - packaging=23.2
  - pandas=2.1.1
  - paramiko=3.3.1
  - parso=0.8.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.11.0
  - ply=3.11
  - prometheus_client=0.17.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=3.20.3
  - psutil=5.9.5
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2021.3
  - pywin32=306
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - querystring_parser=1.2.4
  - re2=2022.04.01
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.11.2
  - setuptools=68.2.2
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.10
  - sqlalchemy=2.0.21
  - sqlite=3.43.0
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tbb=2021.6.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.3.3
  - traitlets=5.11.2
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=1.26.17
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - waitress=2.1.2
  - wcwidth=0.2.8
  - websocket-client=1.6.3
  - werkzeug=3.0.0
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5